### ISSUE TITLE
gulpjs css compile hakkında bir soru

### ISSUE THREAD

**Issue by ademilter** [ademilter/AMA#10]
> selam adem abi. videolarının cogunu izliyorum zaman buldukça. bir sorum var müsait zamanında cevaplarsan çok memnun olurum.
> 
> şimdi abi ben abi senin videonda yola çıkarak bootstrap scss dosyalarını css olarak gulp ile compile ediyorum. ama ben ekstradan kendim bir scss dosyası yazmak istiyorum. bunuda farklı isimle compile etmek istiyorum. yani bir tanesi "bootstrap.css" oldu diyelim diğeri de "main.css" olsun istiyorum. çift css çıktısı kısacası. şimdi bunun için iki ayrı task mi olusturmam lazım gulp'da yoksa daha kısa yolu var mı

**Comment by ademilter** [comment]
selam ebubekir,
ayri task olusturman daha saglikli olur. ama neden bootstrap'i compile ediyorsun onu merak ettim. normalde bootstrap gibi kutuphaneler, sikistirilmis dosyasi sayfanin en ustune koyulur. ekstra yazdigin dosyayi gulp'dan gecirir bootstrap'in hemen altina eklersin.

aksi takdirde, bootstrap buyuk bir kutuphane oldugu icin compile suresi uzun surer ve sayfa yenileme suresi uzar. bu da gelistirme ortami icin gereksiz bekleme surelerine sebep olur. eger bootstrap'i ozellestirmek icin boyle bir sey yapiyorsan bile bunu sadece bir defa yapip istedigin ciktiyi alip bir daha ellemezsin.

**Comment by erayaydin** [comment]
[Theming Bootstrap](https://getbootstrap.com/docs/4.0/getting-started/theming/) burada belirtildiği gibi, kendi frontend scss dosyasında `bootstrap` tan gerekli içe aktarmaları yapıp, değişkenleri özelleştirmesi daha iyi olmaz mı? Bağımlıkları(`vendors.css`) veya daha güzeli tüm uygulamayı tek bir `app.css` içerisinde toplamak daha mantıklı olacaktır diye düşünüyorum. Zaten web servis, değişmediği durumlarda 304 ile `Not Modified` verecektir.

Bir çok projenin reposunda da bu şekilde yapıldığını gördüm. Bahsettiğim örnek şu şekilde [laravel/app.scss](https://github.com/laravel/laravel/blob/master/resources/sass/app.scss)
