### ISSUE TITLE
Vue için justified gallery çözümü 

### ISSUE THREAD

**Issue by gorkie** [ademilter/AMA#12]
Merhaba,

Vue içerisinde kullanacağım yatay rowlardan oluşan ve justified şekilde hizalanmış bir galeri grid yapısı oluşturmak istiyorum ancak vue ile uyumlu sorun çıkarmayan bir plugin bulamadım. Aşağıdaki örnek linkte olacak şekilde bir yapıyı nasıl hazırlayabilirim? Yada vue component içerisinde kullanabileceğim benzer bir yapı var mıdır? 

Örnek yapı:
https://depositphotos.com/search/pizza.html

Bu konuda bana yardımcı olabilirseniz çok sevinirim, teşekkürler.

Görkem.

**Comment by gorkie** [comment]
Merhaba,

İçerik alanından bahsediyorum. Aşağıya ekran görüntüsünü olarak ekledim. 

<img width="1592" alt="screen" src="https://user-images.githubusercontent.com/16632488/48678900-bd67fd80-eb9a-11e8-96c8-7c7f08b949a8.png">

**Comment by ademilter** [comment]
Bununla alakalı okuduğum en iyi kaynak şu yazı
https://link.medium.com/fAC6ACclXR

İlk aklıma gelen bu olduğu için yazıyorum. Eklentiye denk gelirsem tekrar yazarım

**Comment by gorkie** [comment]
Çok teşekkürler, bende hemen inceleyeceğim.
