### ISSUE TITLE
İş Görüşmeleri İçin Kullandığınız İletişim Kanalı

### ISSUE THREAD

**Issue by hasancemreok** [ademilter/AMA#16]
Merhaba Adem Bey,

İş görüşmesi yapmak için kullandığınız bir mail adresiniz ve ya bir iletişim kanalı var mı ? Business konularda size hangi kanaldan ulaşalım ? Bir arayışta olduğumuzda sizi bundan nasıl haberdar edebilirim ?

Teşekkürler.

**Comment by ademilter** [comment]
Merhaba Hasan,
Bu tür iş teklifi ve gizlilik önemli olan maillere direkt ademilter @ gmail üzerinden cevap veriyorum.
