### ISSUE TITLE
Webstorm Ayarları Hk.

### ISSUE THREAD

**Issue by ghost** [ademilter/AMA#17]
Merhaba,

Videolarınızı izlerken Webstorm ortamınızı çok beğendim. Bununla ilgili olarak theme, font, settings ayarlarınızı paylaşmanız mümkün müdür? 

Teşekkürler :)

**Comment by ademilter** [comment]
Merhaba Alp,

- [Dark Purple Theme](https://plugins.jetbrains.com/plugin/12100-dark-purple-theme)
- [JetBrains Mono typeface](https://www.jetbrains.com/lp/mono/)
