### ISSUE TITLE
Css Serisi devamı

### ISSUE THREAD

**Issue by kerem66** [ademilter/AMA#18]
Merhaba, Twitter üzerinden css derslerine devam ediceğinizi söylediniz. Serinin devamı ile ilgili videoları yayınlamak için aklınızda tahmini bir tarih var mı? Bilgilendirebilirseniz çok sevinirim. Teşekkürler.

**Comment by ademilter** [comment]
Merhaba Kerem, 2-3 gün içinde kaldığımız yerden devam edeceğiz.
