### ISSUE TITLE
Javascript Trickler Hk.

### ISSUE THREAD

**Issue by berat** [ademilter/AMA#22]
Selamlar, 

React native videosunu izlediğim zaman sizden çok güzel trickler kaptım. Bu trickler gerçekten harika. Trickleri bilmeden önce çok fazla çaba sarf ediyorum ve bunu artık engelemek için trickleri öğrenmek istiyorum. Büyük ihtimal twitter hesaplarından öğreniyorsunuz bunu. Hesapları bizimle paylaşma imkanınız var mı?

Sevgiler!

**Comment by ademilter** [comment]
Merhaba Berat,
Bahsettiğin ipuçları ve kısayollar zamanla kazanılan özellikler. Açık kaynak projelere katkı yapmak ve projene katkı yapılmasını sağlamak çok önemli burada. Diğer insanların yöntem ve tecrübelerinden faydalanmak çok şey katacaktır. Özellikle tecrübesine güvendiğin iyi geliştiricilerin veya şirketlerin kodlarını incelemeni ve neyi neden yaptığını sorgulaman gerekli. Kitap okumak gibi kod okumaya da zaman ayırmayı dene. Mesela vue, jquery, lodash gibi paketlerin kaynak kodlarını incelemeni tavsiye ederim.

Özellikle fonksiyonel programlama paradigmalarını okumak da çok şey katacaktır. Her işi küçük bir kod parçası haline getirmeyi öğretiyor.
