### ISSUE TITLE
Kullandığın iterm teması nedir ? 

### ISSUE THREAD

**Issue by camaronur** [ademilter/AMA#23]
Videolarında kullandığın terminal iterm sanırım bunda kullandığın tema nedir?

**Comment by ademilter** [comment]
Merhaba Onur,

- [iTerm2](https://www.iterm2.com/)
- [ohmyz](https://ohmyz.sh/)
- [theme snazzy](https://github.com/sindresorhus/iterm2-snazzy)
- [JetBrains Mono typeface](https://www.jetbrains.com/lp/mono/)
