### ISSUE TITLE
Mentorluk

### ISSUE THREAD

**Issue by memins** [ademilter/AMA#26]
Merhaba,

ben junior web development olarak çalışıyorum..
ama bazı konularda açamilik yaşıyorum... çalıştığım firmada senior yazılımcı benden daha çok diğer işlerler uğraşıyor... bende kendimi geliştirmeye gayret ediyorum ama yetersiz kalıyorum gibi...

Udemy, Frontendmasters den dersler aldım ama onlarda çok basic kaldı...
biraz araştırdım... böyle bir durumu her yazılımcının başından geiyormuş... ve bu konuda mentorla çalışmak iyi olabilir dediler... sizin bu konuda görüşünüz nedir?

sizde mentörlük veriyormusunuz?

**Comment by ademilter** [comment]
1,5 ay önce yazdığın mesaja yeni bakıyorum ve ilk baktığım şey github profilin oldu :)

çok güzel projeler, örnekler yapmışsın kesinlikle böyle devam etmelisin ama örneklerden gerçek bir projeye geçmen daha faydalı olacaktır. aklına gelen basit bir fikri uygulayıp yayınlayana kadar bütün süreçleri anlayarak yapmaya başla. gerçek bir projenin sana katacakları çok fazla olacaktır. hatta yapabiliyorsan birilerine kullandır.

mentörlük için pek zamanım yok, samimiyetle söylüyorum çok güzel ilerliyorsun. son commit'in "23 saat önce" yazıyor, bunu gördüğüm için bunları rahatlıkla söylüyorum.

**Comment by memins** [comment]
teşekkür ederim ... dediklerinizi dikkate alıp en kısa zamanda gerçek bir proje yapacam inşallah
