### ISSUE TITLE
Frontend öğrenmek için yol haritası?

### ISSUE THREAD

**Issue by ademilter** [ademilter/AMA#6]
Merhabalar Adem Bey,

Bartın Üniversitesi Grafik Tasarım mezunuyum. Sizinle tanışmam Youtube'da videolarınıza denk gelmem ile oldu. 'Sketch Öğreniyorum' videosu bana çok yardımcı oldu, sayenizde Sketch ile tanıştım ve kullanmaya başladım. İlk olarak dersleriniz için teşekkür etmek istiyorum. 'Akşam Oturması' videolarınızda diğer tasarımcı arkadaşlarınızı da tanıma şansım oldu. Rıza Bey'in Facebook'ta çalışması, diğer arkadaşlarınızın oldukça iyi yerlerde olması beni mutlu etti ve ilham verdi. Ben de belki bi' gün oralarda olabilirim diye düşündüm. Bu çalışmalarınız için size tekrardan teşekkür etmek istiyorum.

Bilgi ve deneyimlerinize dayanarak size bir kaç tane sorum var, cevaplayabilirseniz çok mutlu olurum. 

Yaklaşık 2,5 senedir iş hayatında yer alıyorum. Kurumsal kimlik çalışmaları, web ve mobil uygulama tasarımları konusunda zamanla olabildiğince tecrübe kazanmaya çalıştım. Bana en yakın olan web tasarım ve mobil uygulamalar oldu. Yazılım firmalarında çalışarak sektör içerisine girmek istedim.

Bildiğiniz üzere gün geçtikçe yeni teknolojiler çıkıyor, sadece tasarımcı olarak kalmak yetersiz olabiliyor. Ben kendimi olabildiğince geliştirmek istiyorum. Kod yazma konusunda hevesim var. Front-end öğrenmek için çalışmalara başladım.

* Front-end öğrenirken nasıl bi' yol izlememi önerirsiniz?
* Front-end öğrenmem için önerebileceğiniz kaynak siteler var mı? Olabildiğince siteleri araştırıyorum ama tam olarak faydalanabileceğim kaynak bulamadım. 

Diğer önemli bi' konu ise, Kullanıcı Deneyimi. Bu konuda henüz yeniyim. Kullanıcı Deneyimi tasarımına tam olarak nasıl hakim olabilirim, önerebileceğiniz yol var mı?

Şimdiden çok teşekkür ederim. Cevabınızı sabırsızlıkla bekliyorum.

Sevgiler

**Comment by ademilter** [comment]
Yayınladığım videoların işe yaradığını duymak, ilham verdiğini görmek gerçekten mutlu ediyor. Ben teşekkür ederim.

Frontend geliştirici olmak için yol haritasını herkes soruyor, sayısız mail alıyorum. Konu o kadar derin ve detaylı ki, buna doğru cevap vermek ve yönlendirmek tek başıma yapacağım iş değil. Bu konuda, sektörde lider insanlarla ortak bir döküman hazırlayıp sunmak gerekiyor. Adım adım nereden ve nasıl başlayıp hangi aşamalardan geçilmesi gerektiğini anlatan detaylı bir görev listesi. Bunun için ilk tuğlayı benim koymam ve sonrasında insanların katkı yapmasını sağlamak gerekiyor.

Tavsiyem; kendini ya tasarım konusunda geliştirmen ya da frontend konusunda. her ikisini birden yapman pek mümkün görünmüyor, sağlıklı da olmaz. frontend giriş seviyesi bilgilere sahip olabilirsin, bu seni daha iyi bir tasarımcı yapar. zira frontend layout konusunda bilgi sahibi olursan (özellikle responsive) yapacağın tasarımlar daha uygun ve mantıklı olacaktır. Vereceğin gradient veya shadow bile css ile nasıl yapılır bilmen seni diğer tasarımcılardan bir adım öne taşır. Frontend çok derya deniz bir alan yeni çıkan kütüphaneleri takip etmen öğrenmen ve kullanman pek mümkün değil tasarım yaparken. İşi frontend olan biri bile bunların hızına yetişemiyorken :)

Özet geçmem gerekirse, iyi bir tasarımcı nasıl olunur tarafıyla ilgilenmen. Türkiyede sayılı iyi tasarımcı varken, hem yol alman hem öne çıkman daha kolay olacaktır;
https://dribbble.com/designers?twitter=&dribbble=&sort=popular&location=turkey&skills=

Türklerden en favori isimlerim;
https://dribbble.com/kerem
https://dribbble.com/muratgursoy
https://dribbble.com/oykun
https://dribbble.com/sencerbugrahan

Kullanıcı deneyimi konusunda İstanbul'da [Userspots](http://www.userspots.com/), [Sherpa](http://sherpa.digital/) gibi firmalarda çalışmak veya bu firmaların düzenlediği etkinliklere katılman faydalı olacaktır. Yine istanbul'a geldi mesele. İyi pişmek için istanbul şart gibi :)

**Comment by ilker0** [comment]
https://github.com/kamranahmedse/developer-roadmap/blob/master/images/frontend.png
Şöyle bir yol haritası var işine yarayacağını düşünüyorum.
